<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>prjctX: APIs Root</title>
</head>

<body>
    <header>
        <h1>prjctX: APIs Root</h1>
    </header>
    <main>
        <h2>As-salamu alaykum, world! 😊</h2>
        <p>
            <a href="https://en.wikipedia.org/wiki/As-salamu_alaykum" target="_blank">Wikipedia</a>
        </p>
        <div>
            <h3>GET</h3>
            <ul>
                <li><a href="/">/</a></li>
                <li><a href="/collectors">/collectors</a></li>
                <li><a href="/collectors/all">/collectors/all</a></li>
                <li><a href="/collectors/all">/collectors/all</a></li>
                <li><a href="/collectors/all">/collectors/all</a></li>
                <li><a href="/collectors/all">/collectors/all</a></li>
            </ul>
            <a href="#" onclick="window.history.go(-1)">Go Back</a>
        </div>
        <div>
            <h3>POST</h3>
            <ul>
                <li><a href="/">/</a></li>
                <li><a href="/collectors/add">/collectors/add</a></li>
                <li><a href="/collectors/all">/collectors/all</a></li>
                <li><a href="/collectors/all">/collectors/all</a></li>
                <li><a href="/collectors/all">/collectors/all</a></li>
            </ul>
            <a href="#" onclick="window.history.go(-1)">Go Back</a>
        </div>
    </main>
    <footer>
        <p>Copyright © 2023 prjctX. All rights reserved.</p>
        <p><a href="#" target="_top">Homepage</a> | <a href="https://github.com/sabuein/prjctX" target="_blank">Source code</a></p>
    </footer>
</body>

</html>